import Image from 'next/image';
import Link from 'next/link';
import { products } from '../../database/products';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function ProductsPage() {
  // const products = await getProducts();

  return (
    <main>
      This is all products
      {products.map((product) => {
        return (
          <div key={`product-div-${product.id}`}>
            <Link
              data-test-id="product-<product id>" // double check this one !!!
              href={`/products/${product.id}`}
            >
              {product.title}
            </Link>
            <br />
            {/* <Link href={`/products/${product.price}`}>{product.price}</Link> */}
            {product.price}
            <br />
            <Image
              src={`/images/${product.name}.jpg`}
              width={200}
              height={300}
            />
          </div>
        );
      })}
    </main>
  );
}
